### ISSUE TITLE
Add to ldionne/metabench

### ISSUE THREAD

**Issue by JohelEGP** [boost-ext/mp#3]
See https://github.com/ldionne/metabench.

**Comment by krzysztof-jusiak** [comment]
It would be great to have it metabench but it's a lot of effort and metbench is missing IMHO the most important tests which is the combination of different meta-functions, which changes the compilation-time performance quite a bit. I've tried to capture some of that on https://github.com/boost-ext/mp/tree/benchmark, but it still early stages.
