### ISSUE TITLE
Awesome little library! A few quick comments...

### ISSUE THREAD

**Issue by dhollman** [boost-ext/mp#60]
This is so cool! A few random comments (or questions on what I'm missing if I'm wrong about these things):

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L283

I think this should be `and` here?

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L285

This (and several places above) can just use CTAD, right? **[Answering my own question: you can't do CTAD because of the `sizeof...(Ts) == 0` case 🤦🏼‍♀️]**

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L98-L106

Probably not relevant, but this implies that types like `int` and `float*` are callable

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L124-L125

Unsolicited suggestion: while you're at it, I like using `operator+` for concatenation (so that things like `join<TLs...>` can just be implemented as `decltype(TLs{} + ... + type_list<>{})`). Maybe not relevant here, but fun thought for later. Here's where I do this in my toy library `cutempl`: https://github.com/dhollman/cutempl/blob/5bb6cae4423f0456c21e50454bcba210a94226b3/include/cutempl/containers/type_list.hpp#L14-L21

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L389-L393

I believe `expr_fn` doesn't need to be captured here since it's `constexpr`? (In fact, I think it's technically incorrect to do so, but the compiler is just okay with it?)

Also, shouldn't `declval` be a non-ADL call here since it could be ambiguous with `std::declval` if `T` is in `std`?

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L443-L444

Seems like this one could just delegate to the previous overload? Something like `value_list<Vs...> | fn | []<auto... Vvs> { return declval<T<R, Vvs...>>() };` (Obviously omitting some corner cases).

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L486-L488

Seems like `requires requires { []<class... Ts>(std::tuple<Ts...>){}(t()); }` would be a more descriptive/self-documenting constraint here.

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L714-L715

This deduction guide should be unnecessary in C++20 and later

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L706

Is there a reason to do this instead of using the comma operator? (Here and elsewhere; Also, if you do use the comma operator, you should do `((void)expr(Ts), ...)` to work around overloaded comma operators)

---

https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L80-L83

_Really_ nit-picky, but you should ignore digit separators in this loop.

**Comment by dhollman** [comment]
https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L510-L516

It's not clear to me why you should be allowed to use `t()` in a template argument expression here. Seems to work, but I can't exactly figure out why.

**Comment by krzysztof-jusiak** [comment]
Thank you @dhollman very much! Really appreciate the review/feedback which will make the library much cuter.

**Comment by krzysztof-jusiak** [comment]
Closing as new/different version has been released. Thanks again for the comments, all have been addressed.
