### ISSUE TITLE
Statement SFINAE isn't allowed

### ISSUE THREAD

**Issue by dhollman** [boost-ext/mp#61]
https://github.com/boost-ext/mp/blob/73cc0531fdcf1809ba1add3686a647a21de88610/include/boost/mp.hpp#L603-L679

Unfortunately, this only works currently with clang because of a bug. It's not supposed to (according to http://eel.is/c++draft/temp#deduct.general-9.sentence-1, particularly the Note below that)

**Comment by krzysztof-jusiak** [comment]
Oh, thank you @dhollman; that' s a bummer though; it's so much cleaner than the any_type arity stuff but will have to switch; thanks for pointing it out :bow:

**Comment by ecatmur** [comment]
This is CWG 2672 https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2672
I opened https://github.com/llvm/llvm-project/issues/64138 to clang.

**Comment by krzysztof-jusiak** [comment]
Thanks, reflection has been moved to https://github.com/boost-ext/reflect.
