### ISSUE TITLE
parameter pack filter and reorder

### ISSUE THREAD

**Issue by feverzsj** [boost-ext/mp#66]
Is it possible to filter and reorder a parameter pack?

```c++
void foo(auto&&... args)
{
    qoo(std::forward_as_tuple(std::forward<decltype(args)>(args)...)
        | std::views::filter(???)
        | std::views::reverse);
}
```

**Comment by krzysztof-jusiak** [comment]
Yeah, that's possible with the previous version and the current version.

For the previous version - https://godbolt.org/z/v5qss7WE7
For the current version - https://godbolt.org/z/cqz9KEzra
